name: Deploy Frontend

on:
  push:
    branches: [main]
    paths: ['frontend/**']

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g vercel@latest
      - run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: frontend
        env:
          VERCEL_ORG_ID: team_8KloincKc12feu3HqoGUlX54
          VERCEL_PROJECT_ID: prj_qTqBSeBRLAo2aCRbRxcJCfbD7op5
